
#define CONFIG_DIFFTEST_REF_NAME "nemu"
#define CONFIG_ENGINE "interpreter"
#define CONFIG_WATCHPOINT 1
#define CONFIG_PC_RESET_OFFSET 0x0
#define CONFIG_DIFFTEST_REF_SPIKE 1
#define CONFIG_TARGET_NATIVE_ELF 1
#define CONFIG_MSIZE 0x8000000
#define CONFIG_CC_O2 1
#define CONFIG_DEVICE 1
#define CONFIG_MODE_SYSTEM 1
#define CONFIG_BUF_SIZE 16
#define CONFIG_WAVE_TRECE 1
#define CONFIG_DIFFTEST 1
// #define Performance
#define CONFIG_HAS_SERIAL 1
#define CONFIG_ISA_riscv 1
#define CONFIG_TRACE_END 10000
#define CONFIG_CC_ASAN 1
#define CONFIG_SERIAL_INPUT_FIFO 1
#define CONFIG_MBASE 0x80000000
#define CONFIG_TIMER_GETTIMEOFDAY 1
#define CONFIG_ENGINE_INTERPRETER 1
#define CONFIG_CC_OPT "-O2"
#define CONFIG_SERIAL_MMIO 0xa00003f8
#define CONFIG_TIMER 0x02000000
#define CONFIG_RT_CHECK 1
#define CONFIG_ITRACE_COND "true"
#define CONFIG_PMEM_MALLOC 1
#define CONFIG_CC "gcc"
#define CONFIG_DIFFTEST_REF_PATH "none"
#define CONFIG_CC_DEBUG 1
#define CONFIG_TRACE_START 0
#define CONFIG_CC_GCC 1
//#define CONFIG_MTRACE 1
#define CONFIG_ISA "riscv32"
//#define CONFIG_ITRACE 1
//#define CONFIG_RVE  1
// #define CONFIG_FTRACE 1
// #define CONFIG_FUNCSIZE 50
// #define CONFIG_FUNCLINESIZE 60
// #define CONFIG_FUNCNUM 100
//#define NVBOARD